### PR TITLE
Notify user when trying to launch nonexistent linked channel

### LINKED ISSUE #979: Nonexistent linked channels silently fail
When adding a new channel that links to nothing, no error is thrown, and when launching that nonexistent channel, again, no error is thrown.
```sh
$ juliaup link mychannel does_not_exist
$ echo $?
0
$ julia +mychannel
$ echo $?
0
$
```

### PR DESCRIPTION
**Pull request by christiangnrd**
Only warn when adding nonexistent julia install, as I find it useful to be able to add the link before I have the julia binary.

Fixes #979

### CODE REVIEW

File: src/bin/julialauncher.rs [hunk 1]
```diff
@@ -393,9 +395,16 @@ fn run_app() -> Result<i32> {
             }
 
             // replace the current process
-            std::process::Command::new(julia_path)
-                .args(&new_args)
-                .exec();
+            if is_valid_julia_path(&julia_path) {
```
Comment (davidanthoff) [inline src/bin/julialauncher.rs:398]: Hm, this will essentially add a complete Julia launch into the path before we _actually_ start Julia, right? I think that would add too much overhead.

I would assume that we can instead just handle the error if the `exec` command doesn't succeed?

**Review by davidanthoff — CHANGES_REQUESTED** [review]
I think the check on launch we can do in some other way, but the check on link seems good as is.

File: src/bin/julialauncher.rs (hunk 1 above)
Comment (christiangnrd) [reply src/bin/julialauncher.rs]: Your suggestion seems to work!

**Review by davidanthoff — APPROVED** [review]
