### PR TITLE
query to code sign PR builds on mac

### LINKED ISSUE #1000: Warn user and get opt-in for +pr mode
On MacOS it's not possible to use the `+pr...` mode because the binaries are not codesigned, given that they are non-merged PRs.

We should do something this on MacOS
```
% juliaup add +pr51811
Installing Julia pr51811-macos-aarch64
As this is a non-merged PR it has not been codesigned. Would you like to locally codesign this to make it run? Note that it is your responsibility to review for security issues with the PR.
Locally codesign? y/[n]:
```

And perhaps on platforms that don't codesign check before installing the files
```
% juliaup add +pr51811
This is a PR that may not have been merged. Note that it is your responsibility to review for security issues with the PR.
Continue installation? y/[n]:
```

---

In testing this I signed with:

sign_binaries.sh
```
#!/bin/bash

# Function to sign a binary
sign_binary() {
    local binary="$1"
    echo "Signing $binary"
    codesign --sign - "$binary"
}

# Export the function for use with find
export -f sign_binary

# Find and sign all binaries in the current directory and its subdirectories
find . -type f -perm +111 -exec bash -c 'sign_binary "$0"' {} \;

echo "All binaries signed."
```

But note that stdlibs will re-precompile because codesigning changes their mtime/hash (on buildkite we update the .ji cache file headers after codesigning)

### LINKED ISSUE #1127: `-pr{number}` build's libjulia has invalid code signature on macOS
The PR builds seem to have an invalid code signature on macOS:

```bash
> codesign -vv ~/.julia/juliaup/julia-pr56801/lib/libjulia.1.12.0.dylib
/Users/mcranmer/.julia/juliaup/julia-pr56801/lib/libjulia.1.12.0.dylib: invalid signature (code or signature have been modified)
In architecture: arm64

> codesign -vv ~/.julia/juliaup/julia-1.11.2+0.aarch64.apple.darwin14/lib/libjulia.1.11.dylib
/Users/mcranmer/.julia/juliaup/julia-1.11.2+0.aarch64.apple.darwin14/lib/libjulia.1.11.dylib: valid on disk
/Users/mcranmer/.julia/juliaup/julia-1.11.2+0.aarch64.apple.darwin14/lib/libjulia.1.11.dylib: satisfies its Designated Requirement
```

which leads to the PR channel builds crashing without any error messages: https://github.com/JuliaLang/juliaup/issues/1126.

### PR DESCRIPTION
**Pull request by KristofferC**
Fixes #1127
Fixes #1000 

Usage example:

```
~/juliaup main*
❯ ./target/debug/juliaup add pr59847   
Installing Julia pr59847-macos-aarch64

WARNING: PR builds are not code-signed for macOS.
The Julia binary will fail to run unless you codesign it locally.

Would you like to automatically codesign this PR build now? [y/N]: y

Codesigning Julia binary...
/Users/kc/.julia/juliaup/julia-pr59847/bin/julia: replacing existing signature
Codesigning Julia library...
/Users/kc/.julia/juliaup/julia-pr59847/lib/libjulia.1.13.0.dylib: replacing existing signature
/Users/kc/.julia/juliaup/julia-pr59847/lib/libjulia.dylib: replacing existing signature
/Users/kc/.julia/juliaup/julia-pr59847/lib/libjulia.1.13.dylib: replacing existing signature
✓ Codesigning completed successfully.

~/juliaup main* 20s
❯ ./target/debug/julia +pr59847        
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.13.0-DEV.1316 (2025-10-16)
 _/ |\__'_|_|_|\__'_|  |  kc/bracket_complete/6f38ab386b4 (fork: 1 commits, 2 days)
|__/                   |

julia> VERSION
v"1.13.0-DEV.1316"
```

Mostly built with Claude Code 🤖

### CODE REVIEW

File: src/command_add.rs [hunk 1]
```diff
@@ -110,5 +110,76 @@ fn add_non_db(channel: &str, paths: &GlobalPaths) -> Result<()> {
     if config_file.data.settings.create_channel_symlinks {
         create_symlink(&config_channel, &format!("julia-{}", channel), paths)?;
     }
+
+    // Handle codesigning for PR builds on macOS
+    #[cfg(target_os = "macos")]
+    if Regex::new(r"^pr\d+").unwrap().is_match(channel) {
```
[the remark this answers is not in the document]
Comment (KristofferC) [reply src/command_add.rs:128]: The performance cost of compiling a regex here is negligible.

**Comment by IanButterworth** [comment]
Nice. Did you not need to sign the stdlibs?

**Comment by KristofferC** [comment]
Nope, Claude said that those had no signature at all while the julia itself and libjulia had a signature that was invalid which caused the crash..

**Comment by IanButterworth** [comment]
Ah ok

**Comment by KristofferC** [comment]
I guess for unsigned it does the web lookup but for invalid signed it just gives up straight away.. 🤷

File: src/command_add.rs [hunk 2]
```diff
@@ -110,5 +110,76 @@ fn add_non_db(channel: &str, paths: &GlobalPaths) -> Result<()> {
...
+
+    Ok(())
+}
+
+#[cfg(target_os = "macos")]
+fn codesign_pr_build_if_needed(channel: &str, paths: &GlobalPaths) -> Result<()> {
+    use std::io::{self, Write};
+
+    eprintln!("\nWARNING: PR builds are not code-signed for macOS.");
+    eprintln!("The Julia binary will fail to run unless you codesign it locally.");
```
Comment (IanButterworth) [inline src/command_add.rs:143]: I know that this just works on other platforms, but I feel it should be spelled out given we're asking to work around the block.

```suggestion
    eprintln!("Note that unmerged PRs may not have been reviewed for security issues etc.");
    eprintln!("The Julia binary will fail to run unless you codesign it locally.");
```

Comment (IanButterworth) [reply src/command_add.rs:143]: I guess we could move that message earlier when adding the channel, so it shows on all platforms.

Comment (DilumAluthge) [reply src/command_add.rs:143]: I do think it's valuable to have at the time of doing the ad hoc codesigning, which is intentionally bypassing a macOS security restriction.

So I think I'd either do:
1. Show at both times (at channel install time, and again every time we ad hoc codesign).
2. Show every time we ad hoc codesign.

But I wouldn't show it only one time at channel install time.

Comment (KristofferC) [reply src/command_add.rs:143]: I don't think it makes sense to show it on one platform when it is the same code that runs.

Comment (DilumAluthge) [reply src/command_add.rs:143]: Well we aren't ad hoc codesigning on other platforms.

Comment (IanButterworth) [reply src/command_add.rs:143]: Added one here with a url for easy access https://github.com/JuliaLang/juliaup/pull/1278

Comment (KristofferC) [reply src/command_add.rs:143]: > Well we aren't ad hoc codesigning on other platforms.

I don't see how that matters, the code runs the same. Having a common warning for all platforms makes sense, though.

Comment (DilumAluthge) [reply src/command_add.rs:143]: #1278 looks good to me

**Comment by IanButterworth** [comment]
I think adding a test for this would be quite difficult, so confirming it works locally at least.

```
% ./target/release/juliaup add pr59893

WARNING: Note that unmerged PRs may not have been reviewed for security issues etc.
Review code at https://github.com/JuliaLang/julia/pull/59893

Installing Julia pr59893-macos-aarch64

WARNING: PR builds are not code-signed for macOS.
The Julia binary will fail to run unless you codesign it locally.

Would you like to automatically codesign this PR build now? [Y/n]: 

Codesigning Julia binary...
/Users/ian/.julia/juliaup/julia-pr59893/bin/julia: replacing existing signature
Codesigning Julia library...
/Users/ian/.julia/juliaup/julia-pr59893/lib/libjulia.1.13.0.dylib: replacing existing signature
/Users/ian/.julia/juliaup/julia-pr59893/lib/libjulia.dylib: replacing existing signature
/Users/ian/.julia/juliaup/julia-pr59893/lib/libjulia.1.13.dylib: replacing existing signature
✓ Codesigning completed successfully.
ian@Ians-MacBook-Pro juliaup % ./target/release/julia +pr59893  
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.13.0-DEV.1334 (2025-10-18)
 _/ |\__'_|_|_|\__'_|  |  DilumAluthgeBot:BumpStdlibs/JuliaSyntaxHighlighting-2817dba-master/4997e0a0dc5 (fork: 1 commits, 1 day)
|__/                   |

julia> 
```
